This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file H:/part3_project/Report/report.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file report.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file report.acr....done (9 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
